apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: coolstuff-app
  namespace: tekton-workshop
spec:
  url: "https://gitea-server-gitea.apps.cluster-flqhr.flqhr.sandbox5312.opentlc.com/user1/coolstuff-app"
  git_provider:
    secret:
      name: "gitea-pac-secret"
      key: "provider.token"
    webhook_secret:
      name: "gitea-pac-secret"
      key: "webhook.secret"
