apiVersion: v1
kind: Secret
metadata:
  name: gitea-pac-secret
  namespace: tekton-workshop
type: Opaque
stringData:
  provider.token: "16ccf5cfc40da4b868e193607bdc6a976f4379ce"
  webhook.secret: "1f6af752ee875202d233edfed24309dd255b2455"
