---
site:
  title: "Building Pipelines using Tekton on OpenShift"
  url: https://github.com/meklund/tekton-workshop
  start_page: modules::index.adoc

content:
  sources:
    - url: /antora
      start_path: content      

ui:
  bundle:
    url: "https://github.com/rhpds/rhdp_showroom_theme/releases/download/v0.0.1/ui-bundle.zip"
    snapshot: true
  supplemental_files: ./content/supplemental-ui

runtime:
  fetch: true

output:
  dir: ./www
