---
site:
  title: "Building Pipelines using Tekton on OpenShift"
  url: https://github.com/meklund/tekton-workshop
  start_page: modules::index.adoc

content:
  sources:
    - url: .
      start_path: content      

asciidoc:
  attributes:
    #title: Template Tutorial(Dev Mode)
    experimental: true
    openshift-version: 4.20
    #project-namespace: workshop
    page-pagination: true    
    release-version: master
  extensions:
    - ./content/lib/tab-block.js
    - ./content/lib/remote-include-processor.js

ui:
  bundle:
    url: https://github.com/redhat-scholars/course-ui/releases/download/v0.1.14/ui-bundle.zip
    #url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/rh-one-2025/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ./content/supplemental-ui
    - path: ./content/lib
    - path: .nojekyll
    - path: ui.yml
      contents: "static_files: [ .nojekyll ]"

runtime:
  fetch: true

output:
  dir: ./gh-pages
